#!/bin/bash

# Court Kiosk - Vercel Setup Verification Script
echo "🚀 Court Kiosk - Vercel Setup Verification"
echo "=========================================="
echo ""
echo "📋 Current Vercel Configuration:"
echo ""
echo "✅ Build Command: cd frontend && npm run build"
echo "✅ Output Directory: frontend/build"
echo "✅ Install Command: cd frontend && npm install"
echo "✅ Rewrites: All routes go to /index.html (SPA routing)"
echo ""
echo "🔧 Environment Variables to Set in Vercel:"
echo ""
echo "1. REACT_APP_API_URL"
echo "   Value: https://court-kiosk.onrender.com"
echo "   Description: Points frontend to your Render backend API"
echo ""
echo "2. REACT_APP_KIOSK_MODE"
echo "   Value: false"
echo "   Description: Disables kiosk mode for normal web usage"
echo ""
echo "🌍 Your System Architecture:"
echo ""
echo "Frontend (Vercel):"
echo "  - React app served from Vercel CDN"
echo "  - All API calls go to Render backend"
echo "  - Global accessibility"
echo ""
echo "Backend (Render):"
echo "  - Flask API at https://court-kiosk.onrender.com"
echo "  - All 69+ California Court forms"
echo "  - Email service with Resend"
echo "  - Queue management system"
echo ""
echo "✅ Your Court Kiosk should now deploy successfully to Vercel!"
echo ""
